name: gebeta_gl_web
description: Web platform implementation of gebeta_gl. This package is only intended to be used by the gebeta_gl package.
version: 0.20.7
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapLibreMapPlugin
        fileName: gebeta_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^4.0.17
  js: ">=0.6.7 <0.8.0"
  gebeta_gl_platform_interface: ^0.20.5
  meta: ^1.3.0

dev_dependencies:
  very_good_analysis: ^5.0.0

platforms:
  web:
