name: gebeta_gl
description: A Flutter plugin for integrating MapLibre Maps inside a Flutter application on Android, iOS and web platforms.
version: 0.21.9
repository: https://github.com/rav3n11/gebeta-map-futter-public
issue_tracker: https://github.com/rav3n11/gebeta-map-futter-public/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  gebeta_gl_platform_interface: ^0.20.5

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.gebeta.gebetagl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: gebeta_gl_web
  assets:
    - assets/icons/gebeta.png

platforms:
  android:
  ios:
  web:
